extern const GeoLayout WaterCube[];
extern u8 WaterCube_AdvGgtDimInd01_ia8[];
extern u8 WaterCube_wild_wave01_ia8[];
extern Vtx WaterCube_Cube_019_mesh_layer_4_vtx_0[47];
extern Gfx WaterCube_Cube_019_mesh_layer_4_tri_0[];
extern Vtx WaterCube_Cube_019_mesh_layer_4_vtx_1[122];
extern Gfx WaterCube_Cube_019_mesh_layer_4_tri_1[];
extern Gfx mat_WaterCube_water_no_nsolid[];
extern Gfx mat_revert_WaterCube_water_no_nsolid[];
extern Gfx mat_WaterCube_water[];
extern Gfx mat_revert_WaterCube_water[];
extern Gfx WaterCube_Cube_019_mesh_layer_4[];
extern Gfx WaterCube_material_revert_render_settings[];
