#include "src/game/envfx_snow.h"

const GeoLayout castle_grounds_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(1, -4755, -13, 2020, castle_grounds_dl_Cube_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(5, castle_grounds_dl_Cube_mesh_layer_5),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(1, 0, -111, 0, castle_grounds_dl_Cylinder_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(4, castle_grounds_dl_Cylinder_mesh_layer_4),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(1, -2943, -194, 984, castle_grounds_dl_Cylinder_001_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 0, -111, 0, castle_grounds_dl_Cylinder_002_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 0, -111, 0, castle_grounds_dl_Cylinder_003_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, -2952, 746, 986, castle_grounds_dl_Dorrie_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 0, -692, 0, castle_grounds_dl_Effect_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 2191, 317, -1568, castle_grounds_dl_inverted_pyramid_001_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 2674, 317, 126, castle_grounds_dl_inverted_pyramid_002_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 1802, -125, 2924, castle_grounds_dl_Volcano_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(5, 0, -111, 0, castle_grounds_dl_Water_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout castle_grounds_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0x0001),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -50, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, castle_grounds_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(4, castle_grounds_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, castle_grounds_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, castle_grounds_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
