This file will contain instructions on how to import RM2C data into the sm64ex-alo repo.
First you should always copy the exported folders (/src,/levels,/sound,/text,/textures,/actors) into your repo.
Then make sure you set RM2C inside the makefile to 1
Then to build for PC use this input to terminal: "make clean && make -j4 TARGET_N64=0 TARGET_ARCH=native WINDOWS_BUILD=1 TARGET_GAME_CONSOLE=0 DEBUG=1 NODRAWINGDISTANCE=1"
Then to build for N64 use this input to terminal: "make clean && make -j4"
By default, due to their high variability and unique names, no actor data will be included from RM2C output, you must
go per actor and either copy data from a custom.model.inc.c file to the model.inc.c file, or change the includes in group files.

Level specific models will go into a folder inside of /actors/ with the name of the level they belong to. You must copy these folders
over to their level folders. The directory should match the target level dir, and not overwrite any files. Textures should be pre written
to the target level directories.

Below are some warnings generated by RM2C during extraction.
It is expected to have many warnings for editor files and for roms with lots of custom content.

******************************************************************************************
#flipswitch panel star spawners
Objects without references must have behaviors created for them, be given an existing behavior, or be commented out.
 Level hmc Area 1 has object  Bhv_Custom_0x130002a0 with no known label.
 Level rr Area 2 has object  Bhv_Custom_0x130002a0 with no known label.
 Level ttm Area 1 has object  Bhv_Custom_0x130002a0 with no known label.
******************************************************************************************

Levels with fog in sm64 editor and likely early versions of Rom Manager are completely broken and destroy the levels graphics and most non opaque objects.
I attempt to auto fix these, if there is any issue in these levels check fog first.

 Level bbh Display List DL_bbh_1_0xe0c85e0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bbh Display List DL_bbh_1_0xe0ff168 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ccm Display List DL_ccm_1_0xe0cae40 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ccm Display List DL_ccm_1_0xe0ea960 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level hmc Display List DL_hmc_1_0xe07d3c0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level hmc Display List DL_hmc_1_0xe09e738 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ssl Display List DL_ssl_1_0xe05fe30 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ssl Display List DL_ssl_1_0xe0791b0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level wdw Display List DL_wdw_1_0xe055340 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level wdw Display List DL_wdw_1_0xe067148 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level jrb Display List DL_jrb_1_0xe0ddca0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level jrb Display List DL_jrb_1_0xe115f48 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level thi Display List DL_thi_1_0xe0d3940 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level thi Display List DL_thi_1_0xe0fd9b0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ttc Display List DL_ttc_1_0xe069430 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ttc Display List DL_ttc_1_0xe07da80 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ttc Display List DL_ttc_2_0xe09a760 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ttc Display List DL_ttc_3_0xe0c46b0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level rr Display List DL_rr_2_0xe0bd388 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level castle_grounds Display List DL_castle_grounds_1_0xe07b840 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level castle_grounds Display List DL_castle_grounds_1_0xe09c500 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bitfs Display List DL_bitfs_1_0xe07fc90 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bitfs Display List DL_bitfs_1_0xe0a1de0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level sa Display List DL_sa_1_0xe05bac0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level sa Display List DL_sa_1_0xe06f010 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level lll Display List DL_lll_1_0xe0897a0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level lll Display List DL_lll_1_0xe0affa0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ddd Display List DL_ddd_1_0xe057de0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ddd Display List DL_ddd_1_0xe067e20 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level wf Display List DL_wf_1_0xe0c7fc0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level wf Display List DL_wf_1_0xe0fc910 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ttm Display List DL_ttm_1_0xe082c20 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ttm Display List DL_ttm_1_0xe0a18f8 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ttm Display List DL_ttm_2_0xe0e08e0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
******************************************************************************************

Texture scrolls do not always follow the same format I assume, if this error appears it may have an invalid address which causes a crash.
RM2C will try to find the correct address after noticing the one it has is wrong, if a crash occurs when entering the level check these objects first

 Texture Scroll Object in level hmc area 1 at 0xe036b00 has unrecognized address. Object Has been commented out.
 Texture Scroll Object in level hmc area 1 at 0xe035330 has unrecognized address. Object Has been commented out.
 Texture Scroll Object in level hmc area 1 at 0xe040550 has unrecognized address. Object Has been commented out.
 Texture Scroll Object in level sl area 1 at 0xe044d30 has unrecognized address. Object Has been commented out.
 Texture Scroll Object in level thi area 1 at 0xe037b80 has unrecognized address. Object Has been commented out.

 Texture Scroll Object in level bitfs area 1 at 0xe07a8c0 has unrecognized address. Object Has been commented out.
 Texture Scroll Object in level lll area 1 at 0xe07b970 has unrecognized address. Object Has been commented out.
 Texture Scroll Object in level wmotr area 1 at 0xe027e60 has unrecognized address. Object Has been commented out.
 Texture Scroll Object in level wmotr area 1 at 0xe027e60 has unrecognized address. Object Has been commented out.
 Texture Scroll Object in level wmotr area 1 at 0xe0361d0 has unrecognized address. Object Has been commented out.


Known methods of crashing:
*****************************************************************************
ALL BUILDS
IF CRASH ON BOOT - CHECK SEQUENCES
IF TITLE SCREEN LOOP - CHECK START LEVEL IN TWEAKS.INC.C
IF TEXTURES ARE MESSED UP - ALWAYS CHECK LEVEL FOG FIRST
IF ONLY ALPHA TEXTURES MESSED UP - MOVE FOG GEO LAYOUT TO LAYER 1/4 FROM 4/6
IF CRASH UPON ENTERING A LEVEL, CHECK OBJECTS. IF EDITOR, CHECK SCROLLS FIRST. IF NO OBJECTS BAD CHECK SEQUENCES
*****************************************************************************
N64 BUILD
IF SURFACE NODE POOOL OR SURFACE POOL FULL - ADD MORE TRIS TO EXT BOUNDS.H
IF CRASH ON STAR SELECT - PUSH FORWARD GODDARD SEGMENT IN SEGMENTS.H
*****************************************************************************

MORE ON AUDIO ERRORS:
On N64 build, a lack of proper audio memory allocation will instantly crash the game. If this happens, extend gAudioHeap in buffers.c
If you have issues with certain m64s sounding garbled, extend gAlBankSets in load.c (line 2000 about).
If sound cuts out at certain points, extend values in gAudioSessionPresets.
If background music cuts out after cutscenes end stub seq_player_lower_volume and seq_player_unlower_volume in external.c (will remove volume adjustments from the entire game).
