This file will contain instructions on how to import RM2C data into the sm64ex-alo repo.
First you should always copy the exported folders (/src,/levels,/sound,/text,/textures,/actors) into your repo.
Then make sure you set RM2C inside the makefile to 1
Then to build for PC use this input to terminal: "make clean && make -j4 TARGET_N64=0 TARGET_ARCH=native WINDOWS_BUILD=1 TARGET_GAME_CONSOLE=0 DEBUG=1 NODRAWINGDISTANCE=1"
Then to build for N64 use this input to terminal: "make clean && make -j4"
By default, due to their high variability and unique names, no actor data will be included from RM2C output, you must
go per actor and either copy data from a custom.model.inc.c file to the model.inc.c file, or change the includes in group files.

Level specific models will go into a folder inside of /actors/ with the name of the level they belong to. You must copy these folders
over to their level folders. The directory should match the target level dir, and not overwrite any files. Textures should be pre written
to the target level directories.

Below are some warnings generated by RM2C during extraction.
It is expected to have many warnings for editor files and for roms with lots of custom content.

******************************************************************************************

Levels with fog in sm64 editor and likely early versions of Rom Manager are completely broken and destroy the levels graphics and most non opaque objects.
I attempt to auto fix these, if there is any issue in these levels check fog first.

 Level ccm Display List DL_ccm_1_0xe059470 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ccm Display List DL_ccm_1_0xe0801a0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ssl Display List DL_ssl_1_0xe07b2b0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ssl Display List DL_ssl_1_0xe0abfb8 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bob Display List DL_bob_1_0xe054580 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bob Display List DL_bob_1_0xe076b30 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ttc Display List DL_ttc_1_0xe080200 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ttc Display List DL_ttc_1_0xe0a9390 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level rr Display List DL_rr_1_0xe04a920 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level rr Display List DL_rr_1_0xe0644d0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bitfs Display List DL_bitfs_1_0xe036120 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bitfs Display List DL_bitfs_1_0xe0474c0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level sa Display List DL_sa_1_0xe0918a0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level sa Display List DL_sa_1_0xe0d1c80 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bits Display List DL_bits_1_0xe0baa50 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bits Display List DL_bits_1_0xe0ec3f8 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level wf Display List DL_wf_1_0xe0653f0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level wf Display List DL_wf_1_0xe08fb90 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level wmotr Display List DL_wmotr_1_0xe07ccc0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bowser_2 Display List DL_bowser_2_1_0xe01d190 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bowser_2 Display List DL_bowser_2_1_0xe025a48 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ttm Display List DL_ttm_1_0xe0777d0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.

Known methods of crashing:
*****************************************************************************
ALL BUILDS
IF CRASH ON BOOT - CHECK SEQUENCES
IF TITLE SCREEN LOOP - CHECK START LEVEL IN TWEAKS.INC.C
IF TEXTURES ARE MESSED UP - ALWAYS CHECK LEVEL FOG FIRST
IF ONLY ALPHA TEXTURES MESSED UP - MOVE FOG GEO LAYOUT TO LAYER 1/4 FROM 4/6
IF CRASH UPON ENTERING A LEVEL, CHECK OBJECTS. IF EDITOR, CHECK SCROLLS FIRST. IF NO OBJECTS BAD CHECK SEQUENCES
*****************************************************************************
N64 BUILD
IF SURFACE NODE POOOL OR SURFACE POOL FULL - ADD MORE TRIS TO EXT BOUNDS.H
IF CRASH ON STAR SELECT - PUSH FORWARD GODDARD SEGMENT IN SEGMENTS.H
*****************************************************************************

MORE ON AUDIO ERRORS:
On N64 build, a lack of proper audio memory allocation will instantly crash the game. If this happens, extend gAudioHeap in buffers.c
If you have issues with certain m64s sounding garbled, extend gAlBankSets in load.c (line 2000 about).
If sound cuts out at certain points, extend values in gAudioSessionPresets.
If background music cuts out after cutscenes end stub seq_player_lower_volume and seq_player_unlower_volume in external.c (will remove volume adjustments from the entire game).
