This file will contain instructions on how to import RM2C data into the sm64ex-alo repo.
First you should always copy the exported folders (/src,/levels,/sound,/text,/textures,/actors) into your repo.
Then make sure you set RM2C inside the makefile to 1
Then to build for PC use this input to terminal: "make clean && make RM2CPC"
Then to build for N64 use this input to terminal: "make clean && make -j4"
By default, due to their high variability and unique names, no actor data will be included from RM2C output, you must
go per actor and either copy data from a custom.model.inc.c file to the model.inc.c file, or change the includes in group files.

Level specific models will go into a folder inside of /actors/ with the name of the level they belong to. You must copy these folders
over to their level folders. The directory should match the target level dir, and not overwrite any files. Textures should be pre written
to the target level directories.

If you have exported custom behaviors, check the /data/ folder for exported custom behaviors with labels, and associated disassembled functions with matching labels.
These are provided for reference only, they must be manually integrated into the repo.

Below are some warnings generated by RM2C during extraction.
It is expected to have many warnings for editor files and for roms with lots of custom content.

******************************************************************************************

Levels with fog in sm64 editor and likely early versions of Rom Manager are completely broken and destroy the levels graphics and most non opaque objects.
I attempt to auto fix these, if there is any issue in these levels check fog first.

 Level bbh Display List DL_swoop_geo_0x6006880 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bbh Display List DL_swoop_geo_0x6006758 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bbh Display List DL_swoop_geo_0x6006a88 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bbh Display List DL_swoop_geo_0x6006bd0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bbh Display List DL_swoop_geo_0x6006d00 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bbh Display List DL_dorrie_geo_0x600cfd0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bbh Display List DL_dorrie_geo_0x600c8b8 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bbh Display List DL_dorrie_geo_0x600c468 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bbh Display List DL_dorrie_geo_0x600baf8 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bbh Display List DL_dorrie_geo_0x600dfa8 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bbh Display List DL_dorrie_geo_0x600c030 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bbh Display List DL_dorrie_geo_0x600d440 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bbh Display List DL_dorrie_geo_0x600d6d8 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bbh Display List DL_dorrie_geo_0x600de38 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bbh Display List DL_dorrie_geo_0x600da88 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bbh Display List DL_dorrie_geo_0x600dc60 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bbh Display List DL_dorrie_geo_0x600d8b0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ssl Display List DL_ssl_geo_0005D8_0x7004ae0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ssl Display List DL_ssl_geo_000734_0x70220a8 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ssl Display List DL_ssl_geo_000734_0x70221e8 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ssl Display List DL_ssl_geo_000764_0x70228a8 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ssl Display List DL_ssl_geo_000764_0x70229e8 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ssl Display List DL_ssl_geo_000794_0x7022cf8 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ssl Display List DL_ssl_geo_0007AC_0x70233a8 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level ssl Display List DL_ssl_geo_0007AC_0x70235c0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bob Display List DL_bob_geo_000440_0x700e458 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bob Display List DL_bob_geo_000458_0x700e768 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bob Display List DL_bob_geo_000470_0x700e8a0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level wdw Display List DL_unagi_geo_0x500d268 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level wdw Display List DL_unagi_geo_0x500d468 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level wdw Display List DL_unagi_geo_0x500d668 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level wdw Display List DL_unagi_geo_0x500d828 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level wdw Display List DL_unagi_geo_0x500d050 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level wdw Display List DL_unagi_geo_0x500deb8 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level wdw Display List DL_unagi_geo_0x500e258 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level wdw Display List DL_unagi_geo_0x500cdd0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level wdw Display List DL_unagi_geo_0x500e088 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level wdw Display List DL_unagi_geo_0x500dd08 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level jrb Display List DL_jrb_geo_000978_0x7008fd8 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level jrb Display List DL_jrb_geo_0009B0_0x7009a58 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level jrb Display List DL_jrb_geo_0009E8_0x700a608 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level jrb Display List DL_jrb_geo_000A00_0x700ac68 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level jrb Display List DL_jrb_geo_000930_0x7007ac8 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level jrb Display List DL_jrb_geo_000960_0x70080f8 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level jrb Display List DL_jrb_geo_000900_0x700ae48 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level jrb Display List DL_jrb_geo_000918_0x700afb0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level jrb Display List DL_jrb_geo_000948_0x7007dc8 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level thi Display List DL_hmc_geo_0005A0_0x7022da0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level thi Display List DL_hmc_geo_0005B8_0x7023090 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level thi Display List DL_hmc_geo_0005D0_0x7022aa0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level thi Display List DL_hmc_geo_000548_0x7023bc8 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level thi Display List DL_hmc_geo_000570_0x7023e10 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level thi Display List DL_hmc_geo_000588_0x7024110 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level thi Display List DL_hmc_geo_000530_0x701fff8 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
 Level bowser_2 Display List DL_custom_DL_0e00017c_0x7000fe0 has fog, for editor, fog DLs are heavily edited, potential for gfx errors.
******************************************************************************************

New models are detected by comparing the checksums of textures from the specific model.
The comparison models come from an unedited vanilla rom loaded into Rom Manager.
If a model is in this list, it has either an unrecognized ID or a new texture.
If a model is not in this list, it does not guarantee that it is unedited.

 model bubbly_tree_geo_ in folder tree has a new model or new textures.
 model wooden_door_geo_ in folder door has a new model or new textures.
 model yellow_coin_geo_ in folder coin has a new model or new textures.
 model star_geo_ in folder star has a new model or new textures.
 model castle_geo_000F18_ in folder castle_inside/trap_door has a new model or new textures.
 model castle_geo_001940_ in folder castle_inside/water_level_pillar has a new model or new textures.
 model castle_geo_001530_ in folder castle_inside/clock_minute_hand has a new model or new textures.
 model castle_geo_001548_ in folder castle_inside/clock_hour_hand has a new model or new textures.
 model castle_geo_001518_ in folder castle_inside/areas/2/pendulum has a new model or new textures.
 model castle_geo_000F00_ in folder castle_inside/star_door has a new model or new textures.
 model breakable_box_geo_ in folder breakable_box has a new model or new textures.
 model breakable_box_small_geo_ in folder breakable_box_small has a new model or new textures.
 model exclamation_box_geo_ in folder exclamation_box has a new model or new textures.
 model amp_geo_ in folder amp has a new model or new textures.
 model pokey_head_geo_ in folder pokey has a new model or new textures.
 model wf_geo_000958_ in folder wf/areas/1/15 has a new model or new textures.
 model yoshi_egg_geo_ in folder yoshi_egg has a new model or new textures.
 model custom_DL_0e00017c_ in folder custom_0e00017c has a new model or new textures.
******************************************************************************************

Collision models are loaded via behavior, not alongside the model. This means it can be more difficult to detect where exactly the collision belongs.
I attempt to guess based on what model the collision is first used with, but if I'm not sure, it will be logged here.

 Collision warp_pipe_geo_ in folder warp_pipe is unkown or found to be new. Used with Behavior bhvWarpPipe.
 Collision exclamation_box_geo_ in folder exclamation_box is unkown or found to be new. Used with Behavior bhvExclamationBox.
 Collision Unk_Collision_134272784 in folder Unk_Collision_134272784 is unkown or found to be new. Used with Behavior bhvCheckerboardElevatorGroup.
 Collision purple_switch_geo_ in folder purple_switch is unkown or found to be new. Used with Behavior bhvFloorSwitchHiddenObjects.
 Collision cannon_lid_seg8_dl_080048E0_ in folder cannon_lid is unkown or found to be new. Used with Behavior bhvCannonClosed.
 Collision purple_switch_geo_ in folder purple_switch is unkown or found to be new. Used with Behavior bhvFloorSwitchGrills.
 Collision thwomp_geo_ in folder thwomp is unkown or found to be new. Used with Behavior bhvThwomp.
 Collision castle_geo_000F00_ in folder castle_inside/star_door is unkown or found to be new. Used with Behavior bhvStarDoor.
 Collision cap_switch_geo_ in folder cap_switch is unkown or found to be new. Used with Behavior bhvCapSwitch.
 Collision whomp_geo_ in folder whomp is unkown or found to be new. Used with Behavior bhvSmallWhomp.
 Collision whomp_geo_ in folder whomp is unkown or found to be new. Used with Behavior bhvWhompKingBoss.
 Collision custom_DL_0e00017c in folder custom_0e00017c is unkown or found to be new. Used with Behavior bhvTiltingBowserLavaPlatform.

Known methods of crashing:
*****************************************************************************
ALL BUILDS
IF CRASH ON BOOT - CHECK SEQUENCES
IF TITLE SCREEN LOOP - CHECK START LEVEL IN TWEAKS.INC.C
IF TEXTURES ARE MESSED UP - ALWAYS CHECK LEVEL FOG FIRST
IF ONLY ALPHA TEXTURES MESSED UP - MOVE FOG GEO LAYOUT TO LAYER 1/4 FROM 4/6
IF CRASH UPON ENTERING A LEVEL, CHECK OBJECTS. IF EDITOR, CHECK SCROLLS FIRST. IF NO OBJECTS BAD CHECK SKYBOXES, THEN SEQUENCES
*****************************************************************************
N64 BUILD
IF SURFACE NODE POOOL OR SURFACE POOL FULL - ADD MORE TRIS TO EXT BOUNDS.H
IF CRASH ON STAR SELECT - PUSH FORWARD GODDARD SEGMENT IN SEGMENTS.H
*****************************************************************************

MORE ON AUDIO ERRORS:
On N64 build, a lack of proper audio memory allocation will instantly crash the game. If this happens, extend gAudioHeap in buffers.c
If you have issues with certain m64s sounding garbled, extend gAlBankSets in load.c (line 2000 about).
If sound cuts out at certain points, extend values in gAudioSessionPresets.
On all builds, if an out of bounds array access happens (often with high sequence numbers) the game will crash or have audio issues.
