extern const GeoLayout bowser_1_area_1_geo[];
extern const GeoLayout bowser_1_area_1[];
extern const Collision bowser_1_area_1_collision[];
extern const MacroObject bowser_1_area_1_macro_objs[];
extern Lights1 bowser_1_dl_Fight_Shell_lights;
extern Lights1 bowser_1_dl_Floor_fight_lights;
extern u8 bowser_1_dl_DRA_O_BB_ROCK01_ci4[];
extern u8 bowser_1_dl_DRA_O_BB_ROCK01_ci4_pal_rgba16[];
extern u8 bowser_1_dl_zoo_road_step05_ci4[];
extern u8 bowser_1_dl_zoo_road_step05_ci4_pal_rgba16[];
extern u8 bowser_1_dl_ruinfront_stone_road04_ci4[];
extern u8 bowser_1_dl_ruinfront_stone_road04_ci4_pal_rgba16[];
extern Vtx bowser_1_dl_Icosphere_mesh_layer_1_vtx_0[120];
extern Gfx bowser_1_dl_Icosphere_mesh_layer_1_tri_0[];
extern Vtx bowser_1_dl_Icosphere_mesh_layer_1_vtx_1[10];
extern Gfx bowser_1_dl_Icosphere_mesh_layer_1_tri_1[];
extern Vtx bowser_1_dl_Icosphere_mesh_layer_1_vtx_2[80];
extern Gfx bowser_1_dl_Icosphere_mesh_layer_1_tri_2[];
extern Gfx mat_bowser_1_dl_Fight_Shell[];
extern Gfx mat_revert_bowser_1_dl_Fight_Shell[];
extern Gfx mat_bowser_1_dl_Floor_fight[];
extern Gfx mat_revert_bowser_1_dl_Floor_fight[];
extern Gfx mat_bowser_1_dl_Fight_Border[];
extern Gfx mat_revert_bowser_1_dl_Fight_Border[];
extern Gfx bowser_1_dl_Icosphere_mesh_layer_1[];
extern Gfx bowser_1_dl_material_revert_render_settings[];
