extern const GeoLayout sa_area_1_geo[];
extern const GeoLayout sa_area_1[];
extern const Collision sa_area_1_collision[];
extern const MacroObject sa_area_1_macro_objs[];
extern Lights1 sa_dl_End_floor_lights;
extern Lights1 sa_dl_End_ceill_lights;
extern Lights1 sa_dl_End_WAll_lights;
extern u8 sa_dl_rso_o_my1_road09_ci4[];
extern u8 sa_dl_rso_o_my1_road09_ci4_pal_rgba16[];
extern u8 sa_dl_rso_o_ty1_road01_spc_CI_ci4[];
extern u8 sa_dl_rso_o_ty1_road01_spc_CI_ci4_pal_rgba16[];
extern u8 sa_dl_rso_o_my1_road11CI_ci4[];
extern u8 sa_dl_rso_o_my1_road11CI_ci4_pal_rgba16[];
extern Vtx sa_dl_Plane_002_mesh_layer_1_vtx_0[28];
extern Gfx sa_dl_Plane_002_mesh_layer_1_tri_0[];
extern Vtx sa_dl_Plane_002_mesh_layer_1_vtx_1[27];
extern Gfx sa_dl_Plane_002_mesh_layer_1_tri_1[];
extern Vtx sa_dl_Plane_002_mesh_layer_1_vtx_2[42];
extern Gfx sa_dl_Plane_002_mesh_layer_1_tri_2[];
extern Gfx mat_sa_dl_End_floor[];
extern Gfx mat_revert_sa_dl_End_floor[];
extern Gfx mat_sa_dl_End_ceill[];
extern Gfx mat_revert_sa_dl_End_ceill[];
extern Gfx mat_sa_dl_End_WAll[];
extern Gfx mat_revert_sa_dl_End_WAll[];
extern Gfx sa_dl_Plane_002_mesh_layer_1[];
extern Gfx sa_dl_material_revert_render_settings[];
