#include "src/game/envfx_snow.h"

const GeoLayout bob_area_1_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(1, bob_dl_BezierCurve_mesh_layer_1),
		GEO_DISPLAY_LIST(5, bob_dl_BezierCurve_001_mesh_layer_5),
		GEO_DISPLAY_LIST(1, bob_dl_BezierCurve_002_mesh_layer_1),
		GEO_DISPLAY_LIST(1, bob_dl_BezierCurve_004_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(4, -3636, 913, -609, bob_dl_Cube_005_mesh_layer_4),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(1, bob_dl_Cube_005_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(4, -3680, 1585, 890, bob_dl_Cube_006_mesh_layer_4),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(1, bob_dl_Cube_006_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(4, -1243, 1909, 901, bob_dl_Cube_007_mesh_layer_4),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(1, bob_dl_Cube_007_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(4, -1412, 2222, -545, bob_dl_Cube_008_mesh_layer_4),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(1, bob_dl_Cube_008_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(4, -3636, 2348, -609, bob_dl_Cube_009_mesh_layer_4),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(1, bob_dl_Cube_009_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(4, -3680, 2480, 890, bob_dl_Cube_010_mesh_layer_4),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(1, bob_dl_Cube_010_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_TRANSLATE_NODE_WITH_DL(4, -1243, 2968, 901, bob_dl_Cube_011_mesh_layer_4),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(1, bob_dl_Cube_011_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(5, bob_dl_Ice_001_mesh_layer_5),
		GEO_DISPLAY_LIST(5, bob_dl_Ice_002_mesh_layer_5),
		GEO_DISPLAY_LIST(5, bob_dl_Ignore_Col_mesh_layer_5),
		GEO_TRANSLATE_NODE_WITH_DL(1, -3051, 825, -577, bob_dl_inverted_pyramid_001_mesh_layer_1),
		GEO_DISPLAY_LIST(1, bob_dl_Solid_mesh_layer_1),
		GEO_DISPLAY_LIST(1, bob_dl_Solid_001_mesh_layer_1),
		GEO_DISPLAY_LIST(1, bob_dl_Solid_002_mesh_layer_1),
		GEO_DISPLAY_LIST(4, bob_dl_Solid_003_mesh_layer_4),
		GEO_TRANSLATE_NODE_WITH_DL(1, 7802, 0, 6484, bob_dl_Solid_005_mesh_layer_1),
		GEO_TRANSLATE_NODE_WITH_DL(1, 8524, 1566, 2652, bob_dl_Solid_006_mesh_layer_1),
		GEO_DISPLAY_LIST(5, bob_dl_Water_render_col_mesh_layer_5),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout bob_area_1[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0x0001),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(CAMERA_MODE_8_DIRECTIONS, 0, 0, 0, 0, -250, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, bob_area_1_geo),
					GEO_RENDER_OBJ(),
					GEO_ASM(ENVFX_MODE_NONE, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(4, bob_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, bob_dl_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, bob_dl_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
