COURSE_ACTS(COURSE_BOB, _("1 DOOMED SKY CHAOS LAND"),	_("THIS IS ONLY THE BEGINNING "),	_("A DEMONSTRATION OF SKILLS"),	_("ANOTHER HARSH PARKOUR"),	_("SECRET OF THE TREE"),	_("HIDDEN OR OBVIOUS?"),	_("RED DOOMED COINS"))

COURSE_ACTS(COURSE_WF, _(" 2 SUBMERGED SNOWY TOWN"),	_("THE MAYORS HOUSE"),	_("CHIMNEY OF THE OLD BAR"),	_("SNOW, ICE AND DANGER"),	_("SECRETS OF THE HIGH TOWER"),	_("SLIPPERY COLLECT"),	_("SOMEWHERE IS A STAR"))

COURSE_ACTS(COURSE_JRB, _(" 3 DRILL APOCALYPSE"),	_("UFO MADNESS"),	_("FLOODED TEMPLE"),	_("PATH OF THE STALAGMITE"),	_("THE FALSE VANISHING ROOM"),	_("FORGOTTEN RED COINS "),	_("FIND THE WAY!"))

COURSE_ACTS(COURSE_CCM, _(" 4 TIMELESS TOWN"),	_("UNDER THE GAZEBO"),	_("THE LONELY TREE"),	_("LAST HOUSING TREASURE"),	_("FADING LIGHTHOUSE"),	_("THE MALL'S LAST ITEM"),	_("TIMELESS COINS"))

COURSE_ACTS(COURSE_BBH, _(" 5 HOT SUMMER BEACH"),	_("BIG FISH'S FANCY HOME"),	_("DANGER AT THE BEACH"),	_("BEACH BALL FACTORY ROOF"),	_("CHILLING STAR OF THE BEACH"),	_("FROM ABOVE AND BELOW"),	_("BEACHY RED COINS"))

COURSE_ACTS(COURSE_HMC, _(" 6 EXOTIC DANGER"),	_("AHHHH! IT'S SO HIGH UP!"),	_("SLIPPERY DANGEROUS ROOFS"),	_("HOT STONES"),	_("ZEPPELIN SECRETS"),	_("UNDER THE HOUSE"),	_("SPICY RED COINS"))

COURSE_ACTS(COURSE_LLL, _(" 7 FORBIDDEN WEST WORLD"),	_("A COLD START"),	_("FAR UP IN THE SKY"),	_("THE PATH INSIDE"),	_("HOT SAND KICKING"),	_("CRAZY AND RIDICULOUS PATH"),	_("BLOODY COLD COINS"))

COURSE_ACTS(COURSE_SSL, _(" 8  SPACE DOME CENTER"),	_("FLOATING PLANTS"),	_("CLIMB THE ANTENA"),	_("DROP FROM ABOVE"),	_("FIRE SPEWER AND WINDOWS"),	_("SPACE DOME SECRET EXIT"),	_("WHAT'S RED AND ROUND?"))

COURSE_ACTS(COURSE_DDD, _(" 9 REALM OF COLD MATTERS"),	_("PERFECT WALLKICK"),	_("MOUNTAIN TOP"),	_("OBLIGATORY REDS"),	_("SHELLTASTIK"),	_("THE BLUE FIRE GUIDANCE"),	_("COLD OF TOUCH STAR"))

COURSE_ACTS(COURSE_SL, _("10 BOO'S PRIVATE JAILS"),	_("THE BIG PIPE"),	_("PRISON PIPE EXPLORATION"),	_("SECRETS OF THE BLACK ROOM"),	_("WOW! ANOTHER PIPELINE WORK!"),	_("SLIDE RIGHT INTO IT"),	_("FREE THE RED COINS!"))

COURSE_ACTS(COURSE_WDW, _("11 MANORS OF REALMS"),	_("PERFECT SWIMING"),	_("TOP O' THE MANSION"),	_("CRAZY BASEMENT WALLKICKS"),	_("SUSPENDED BOX OF THE TOWER"),	_("KITCHEN NIGHTMARE"),	_("GHOSTLY ABBADONNED RED COINS"))

COURSE_ACTS(COURSE_TTM, _("12 RESTORED ABYSS"),	_("DEFEAT WHOMP KING EASY NO?"),	_("TRIANGULARY PLATFORMS"),	_("TIME TO CLIMB!"),	_("OLD CABANA"),	_("QUICK WALLKICK"),	_("ABYSSMAL RED"))

COURSE_ACTS(COURSE_THI, _("13 THE LOST CITY"),	_("JUMP. CLIMB AND DON'T FALL"),	_("HIDDEN PATH OF THE WALLKICK"),	_("STAR WITHIN THE BUILDINGS"),	_("BOX JUMPS YES THAT'S EASY"),	_("JUST AN ORDINARY ROOF"),	_("RAGING COINS COLLECTIONS"))

COURSE_ACTS(COURSE_TTC, _("14 PEACEFULL SILENT SNOW"),	_("A TOP OF THE BUILDING"),	_("THE GAP BETWEEN PEACE AND DANGER"),	_("IT WATCHES YOU"),	_("SECRETS BELOW THE GROUNDS"),	_("TASTY PASTA"),	_("IMPOSSIBLE REDS"))

COURSE_ACTS(COURSE_RR, _("15 LAND OF THE BOO'S"),	_("THE SINISTER STATUE"),	_("SIDE OF A CLIFF"),	_("WOODPLANKS IN THE GOOP"),	_("FROM CANNON TO CANNON "),	_("THE GIANT !BOX"),	_("RARE COMMITEMENT"))

SECRET_STAR(15, _("   BOWSER SECRET WORLD"))
SECRET_STAR(16, _("   KING'S PALACE"))
SECRET_STAR(17, _("   THE FINAL CHALLENGE"))
SECRET_STAR(18, _("   DAVID TEN ANTS SLIDE"))
SECRET_STAR(19, _("   LAVA DOMAIN"))
SECRET_STAR(20, _("   THE GIANT MUSHROOM"))
SECRET_STAR(21, _("   SWAMP FOREST"))
SECRET_STAR(22, _("   ECLIPSE OF THE MOON"))
SECRET_STAR(23, _("   ECLIPSE OF THE SUN"))
SECRET_STAR(24, _(""))
CASTLE_SECRET_STARS(_("   KING BOO SECRET STARS"))
EXTRA_TEXT(0,_("ONE OF THE KING BOO'S STOLEN STAR!"))
EXTRA_TEXT(1,_(""))
EXTRA_TEXT(2,_(""))
EXTRA_TEXT(3,_(""))
EXTRA_TEXT(4,_(""))
EXTRA_TEXT(5,_(""))
EXTRA_TEXT(6,_(""))
