COURSE_ACTS(COURSE_BOB, _(" 1 EMPTY FIELD OF EMPTYNESS"),	_("DANGEROUS WALLKICKS"),	_("CLIMB THE HILL"),	_("SECRETS OF THE SECRET SECRETS AND QUICKSAND"),	_("UNDER THE EMPTY PLAINS"),	_("SCALE THE STRUCTURE"),	_("WALK AROUND LIKE AN IDIOT FOR 5 MINUTES"))

COURSE_ACTS(COURSE_WF, _(" 2 COREYS HOUSE"),	_("COREY'S AMAZING CANON SHOT"),	_("TO THE TOP OF THE SPIRAL"),	_("SUCCESS SLIDE"),	_("RED COINS ON THE FLOATING ISLES"),	_("CENTER OF THE VORTEX"),	_("LOL KEK LMAO XD ZOZZLE"))

COURSE_ACTS(COURSE_JRB, _(" 3 LAND OF OTHER ENTRANCES"),	_("-"),	_("--"),	_("---"),	_("----"),	_("-----"),	_("------"))

COURSE_ACTS(COURSE_CCM, _(" 4 COOL, COOL MOUNTAIN"),	_("SLIP SLIDIN' AWAY"),	_("LI'L PENGUIN LOST"),	_("BIG PENGUIN RACE"),	_("FROSTY SLIDE FOR 8 RED COINS"),	_("SNOWMAN'S LOST HIS HEAD"),	_("WALL KICKS WILL WORK"))

COURSE_ACTS(COURSE_BBH, _(" 5 BIG BOO'S HAUNT"),	_("GO ON A GHOST HUNT"),	_("RIDE BIG BOO'S MERRY-GO-ROUND"),	_("SECRET OF THE HAUNTED BOOKS"),	_("SEEK THE 8 RED COINS"),	_("BIG BOO'S BALCONY"),	_("EYE TO EYE IN THE SECRET ROOM"))

COURSE_ACTS(COURSE_HMC, _(" 6 HAZY MAZE CAVE"),	_("SWIMMING BEAST IN THE CAVERN"),	_("ELEVATE FOR 8 RED COINS"),	_("METAL-HEAD MARIO CAN MOVE!"),	_("NAVIGATING THE TOXIC MAZE"),	_("A-MAZE-ING EMERGENCY EXIT"),	_("WATCH FOR ROLLING ROCKS"))

COURSE_ACTS(COURSE_LLL, _(" 7 LETHAL LAVA LAND"),	_("BOIL THE BIG BULLY"),	_("BULLY THE BULLIES"),	_("8-COIN PUZZLE WITH 15 PIECES"),	_("RED-HOT LOG ROLLING"),	_("HOT-FOOT-IT INTO THE VOLCANO"),	_("ELEVATOR TOUR IN THE VOLCANO"))

COURSE_ACTS(COURSE_SSL, _(" 8 SHIFTING SAND LAND"),	_("IN THE TALONS OF THE BIG BIRD"),	_("SHINING ATOP THE PYRAMID"),	_("INSIDE THE ANCIENT PYRAMID"),	_("STAND TALL ON THE FOUR PILLARS"),	_("FREE FLYING FOR 8 RED COINS"),	_("PYRAMID PUZZLE"))

COURSE_ACTS(COURSE_DDD, _(" 9 DIRE, DIRE DOCKS"),	_("BOARD BOWSER'S SUB"),	_("CHESTS IN THE CURRENT"),	_("POLE-JUMPING FOR RED COINS"),	_("THROUGH THE JET STREAM"),	_("THE MANTA RAY'S REWARD"),	_("COLLECT THE CAPS..."))

COURSE_ACTS(COURSE_SL, _("10 SNOWMAN'S LAND"),	_("SNOWMAN'S BIG HEAD"),	_("CHILL WITH THE BULLY"),	_("IN THE DEEP FREEZE"),	_("WHIRL FROM THE FREEZING POND"),	_("SHELL SHREDDIN' FOR RED COINS"),	_("INTO THE IGLOO"))

COURSE_ACTS(COURSE_WDW, _("11 WET-DRY WORLD"),	_("SHOCKING ARROW LIFTS!"),	_("TOP O' THE TOWN"),	_("SECRETS IN THE SHALLOWS & SKY"),	_("EXPRESS ELEVATOR--HURRY UP!"),	_("GO TO TOWN FOR RED COINS"),	_("QUICK RACE THROUGH DOWNTOWN!"))

COURSE_ACTS(COURSE_TTM, _("12 TALL, TALL MOUNTAIN"),	_("SCALE THE MOUNTAIN"),	_("MYSTERY OF THE MONKEY CAGE"),	_("SCARY 'SHROOMS, RED COINS"),	_("MYSTERIOUS MOUNTAINSIDE"),	_("BREATHTAKING VIEW FROM BRIDGE"),	_("BLAST TO THE LONELY MUSHROOM"))

COURSE_ACTS(COURSE_THI, _("13 TINY-HUGE ISLAND"),	_("PLUCK THE PIRANHA FLOWER"),	_("THE TIP TOP OF THE HUGE ISLAND"),	_("REMATCH WITH KOOPA THE QUICK"),	_("FIVE ITTY BITTY SECRETS"),	_("WIGGLER'S RED COINS"),	_("MAKE WIGGLER SQUIRM"))

COURSE_ACTS(COURSE_TTC, _("14 TICK TOCK CLOCK"),	_("ROLL INTO THE CAGE"),	_("THE PIT AND THE PENDULUMS"),	_("GET A HAND"),	_("STOMP ON THE THWOMP"),	_("TIMED JUMPS ON MOVING BARS"),	_("STOP TIME FOR RED COINS"))

COURSE_ACTS(COURSE_RR, _("15 RAINBOW RIDE"),	_("CRUISER CROSSING THE RAINBOW"),	_("THE BIG HOUSE IN THE SKY"),	_("COINS AMASSED IN A MAZE"),	_("SWINGIN' IN THE BREEZE"),	_("TRICKY TRIANGLES!"),	_("SOMEWHERE OVER THE RAINBOW"))

SECRET_STAR(15, _("   BOWSER IN THE DARK WORLD"))
SECRET_STAR(16, _("   BOWSER IN THE FIRE SEA"))
SECRET_STAR(17, _("   BOWSER IN THE SKY"))
SECRET_STAR(18, _("             KACHOW"))
SECRET_STAR(19, _("   CAVERN OF THE METAL CAP"))
SECRET_STAR(20, _("   TOWER OF THE WING CAP"))
SECRET_STAR(21, _("   VANISH CAP UNDER THE MOAT"))
SECRET_STAR(22, _("   LAND OF INVISIBLE WALLS"))
SECRET_STAR(23, _("   THE SECRET AQUARIUM"))
SECRET_STAR(24, _(""))
CASTLE_SECRET_STARS(_("   CASTLE SECRET STARS"))
EXTRA_TEXT(0,_("ONE OF THE CASTLE'S SECRET STARS!"))
EXTRA_TEXT(1,_(""))
EXTRA_TEXT(2,_(""))
EXTRA_TEXT(3,_(""))
EXTRA_TEXT(4,_(""))
EXTRA_TEXT(5,_(""))
EXTRA_TEXT(6,_(""))
