COURSE_ACTS(COURSE_BOB, _(" 1 CHILLY PILLARS"),	_("CALL OF THE SUMMIT"),	_("PENGUIN PANIC"),	_("A REFRESHING SWIM"),	_("HEAVENLY BRIDGE"),	_("8 HOT RED COINS"),	_("PRISONER OF THE BRIDGE"))

COURSE_ACTS(COURSE_WF, _(" 2 LUMINARY TOWERS"),	_("REACH THE THIRD FLOOR"),	_("OPEN SESAME"),	_("TURTLE-LY SAFE SHELL RIDE"),	_("STAR HOPPER"),	_("8 SPARKLING COINS"),	_("JAILED!"))

COURSE_ACTS(COURSE_JRB, _(" 3 SHIFTY SHOW FLOOR"),	_("BOMBS AWAY!"),	_("THE FRAGILE TOWER"),	_("CHUCK THE MARIO!"),	_("COIN BONANZA"),	_("PARKOUR PRESSURE"),	_("THE SHOW MUST GO ON!"))

COURSE_ACTS(COURSE_CCM, _(" 4 ORGAN OASIS"),	_("HEARTBURN"),	_("DIGESTIVE GASES"),	_("ACROSS THE SLIPPERY ARTERY"),	_("CHEW YOUR FOOD PROPERLY!"),	_("PALATAL ACROBATICS"),	_("ERYTHROCYTES, THE RED BLOOD CELLS"))

COURSE_ACTS(COURSE_BBH, _(" 5 REMNANTS OF A TOWN"),	_("SHADOW PLAY"),	_("WALK THE PLANK"),	_("A DESTRUCTIVE MELODY"),	_("PRESERVED BELONGINGS"),	_("SANTA IS A BIT TOO LATE"),	_("GATHER THE REBUILDING FUNDS"))

COURSE_ACTS(COURSE_HMC, _(" 6 SCORCHING JAWS"),	_("A HARD PILL TO SWALLOW"),	_("ACROSS THE SINKING DEBRIS"),	_("IN THE PLUMBER TRAP"),	_("CRAZY JUMPS WITH CRAZY BOXES"),	_("WINGS AND HORNS"),	_("8 BURNING COINS"))

COURSE_ACTS(COURSE_LLL, _(" 7 LEVORA SPHERE"),	_("WELCOME BACK"),	_("HORSESHOE RUINS"),	_("FUNGAL INFESTATION"),	_("THE LONELY BATTLEMENT"),	_("GRAB MY ARM"),	_("COINS OF SORROW"))

COURSE_ACTS(COURSE_SSL, _(" 8"),	_("IN THE TALONS OF THE BIG BIRD"),	_("SHINING ATOP THE PYRAMID"),	_("INSIDE THE ANCIENT PYRAMID"),	_("STAND TALL ON THE FOUR PILLARS"),	_("FREE FLYING FOR 8 RED COINS"),	_("PYRAMID PUZZLE"))

COURSE_ACTS(COURSE_DDD, _(" 9"),	_("BOARD BOWSER'S SUB"),	_("CHESTS IN THE CURRENT"),	_("POLE-JUMPING FOR RED COINS"),	_("THROUGH THE JET STREAM"),	_("THE MANTA RAY'S REWARD"),	_("COLLECT THE CAPS..."))

COURSE_ACTS(COURSE_SL, _("10"),	_("SNOWMAN'S BIG HEAD"),	_("CHILL WITH THE BULLY"),	_("IN THE DEEP FREEZE"),	_("WHIRL FROM THE FREEZING POND"),	_("SHELL SHREDDIN' FOR RED COINS"),	_("INTO THE IGLOO"))

COURSE_ACTS(COURSE_WDW, _("11"),	_("SHOCKING ARROW LIFTS!"),	_("TOP O' THE TOWN"),	_("SECRETS IN THE SHALLOWS & SKY"),	_("EXPRESS ELEVATOR--HURRY UP!"),	_("GO TO TOWN FOR RED COINS"),	_("QUICK RACE THROUGH DOWNTOWN!"))

COURSE_ACTS(COURSE_TTM, _("12"),	_("SCALE THE MOUNTAIN"),	_("MYSTERY OF THE MONKEY CAGE"),	_("SCARY 'SHROOMS, RED COINS"),	_("MYSTERIOUS MOUNTAINSIDE"),	_("BREATHTAKING VIEW FROM BRIDGE"),	_("BLAST TO THE LONELY MUSHROOM"))

COURSE_ACTS(COURSE_THI, _("13"),	_("PLUCK THE PIRANHA FLOWER"),	_("THE TIP TOP OF THE HUGE ISLAND"),	_("REMATCH WITH KOOPA THE QUICK"),	_("FIVE ITTY BITTY SECRETS"),	_("WIGGLER'S RED COINS"),	_("MAKE WIGGLER SQUIRM"))

COURSE_ACTS(COURSE_TTC, _("14"),	_("ROLL INTO THE CAGE"),	_("THE PIT AND THE PENDULUMS"),	_("GET A HAND"),	_("STOMP ON THE THWOMP"),	_("TIMED JUMPS ON MOVING BARS"),	_("STOP TIME FOR RED COINS"))

COURSE_ACTS(COURSE_RR, _("15"),	_("CRUISER CROSSING THE RAINBOW"),	_("THE BIG HOUSE IN THE SKY"),	_("COINS AMASSED IN A MAZE"),	_("SWINGIN' IN THE BREEZE"),	_("TRICKY TRIANGLES!"),	_("SOMEWHERE OVER THE RAINBOW"))

SECRET_STAR(15, _("   QUANTUM QUBE - TILTED"))
SECRET_STAR(16, _("   SPECTRAL SPECTACLE"))
SECRET_STAR(17, _("   A SWEET DELIGHT"))
SECRET_STAR(18, _("   QUANTUM QUBE - YELLOW SIDE"))
SECRET_STAR(19, _("   QUANTUM QUBE - GREEN SIDE"))
SECRET_STAR(20, _("   QUANTUM QUBE - RED SIDE"))
SECRET_STAR(21, _("   QUANTUM QUBE - BLUE SIDE"))
SECRET_STAR(22, _("   QUANTUM QUBE - PURPLE SIDE"))
SECRET_STAR(23, _("   QUANTUM QUBE - ORANGE SIDE"))
SECRET_STAR(24, _(""))
CASTLE_SECRET_STARS(_("   OTHER LEVELS"))
EXTRA_TEXT(0,_("A DELIGHTFUL STAR!"))
EXTRA_TEXT(1,_(""))
EXTRA_TEXT(2,_(""))
EXTRA_TEXT(3,_(""))
EXTRA_TEXT(4,_(""))
EXTRA_TEXT(5,_(""))
EXTRA_TEXT(6,_(""))
